### ISSUE TITLE
Got error on MAC OS

### ISSUE THREAD

**Issue by Tin-Nguyen** [quri/react-bootstrap-datetimepicker#55]
I'm facing the error on my local - MAC OS once importing and using the component in code

Error: Cannot find module 'react-bootstrap-datetimepicker' from '<path-removed>'
    at <path-removed>/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (<path-removed>/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (<path-removed>/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (<path-removed>/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex <path-removed>/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at <path-removed>/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:108:15)

There's any one was facing and resolved this? Please help me thanks

**Comment by dingn1** [comment]
+1
