### ISSUE TITLE
npm run examples fails on Windows

### ISSUE THREAD

**Issue by andrerpena** [quri/react-bootstrap-datetimepicker#70]
Here's the error log:

	C:\Projects\Git\react-bootstrap-datetimepicker>npm run examples

	> react-bootstrap-datetimepicker@0.0.18 examples C:\Projects\Git\react-bootstrap-datetimepicker
	> webpack-dev-server --config ./examples/webpack.config.js

	events.js:85
		  throw er; // Unhandled 'error' event
				^
	Error: listen EADDRINUSE
		at exports._errnoException (util.js:746:11)
		at Server._listen2 (net.js:1146:14)
		at listen (net.js:1172:10)
		at net.js:1270:9
		at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:81:16)
		at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:99:10)

	npm ERR! Windows_NT 6.3.9600
	npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "examples"
	npm ERR! node v0.12.2
	npm ERR! npm  v2.7.4
	npm ERR! code ELIFECYCLE
	npm ERR! react-bootstrap-datetimepicker@0.0.18 examples: `webpack-dev-server --config ./examples/webpack.config.js`
	npm ERR! Exit status 1
	npm ERR!
	npm ERR! Failed at the react-bootstrap-datetimepicker@0.0.18 examples script 'webpack-dev-server --config ./examples/webpack.config.js'.
	npm ERR! This is most likely a problem with the react-bootstrap-datetimepicker package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     webpack-dev-server --config ./examples/webpack.config.js
	npm ERR! You can get their info via:
	npm ERR!     npm owner ls react-bootstrap-datetimepicker
	npm ERR! There is likely additional logging output above.

	npm ERR! Please include the following file with any support request:
	npm ERR!     C:\Projects\Git\react-bootstrap-datetimepicker\npm-debug.log

**Comment by authentik8** [comment]
the `EADDRINUSE` would lead me to think you're probably running another process on that port - have you got any other server programs running that could already be listening on that port?
